# Generated by Django 5.0 on 2023-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='track_inventory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
