# Generated by Django 5.0 on 2024-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='track_inventory',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Track Inventory'),
        ),
    ]
