# Generated by Django 5.0 on 2024-01-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_products_track_inventory'),
        ('invoice', '0002_invoiceitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
